Repository Ziellos05/Laboratorio1-Github, pull requests merged in 2024-03, with the labels that each got.

#2 Agregando función de suma en 3 cifras
  Laboratorio1-Github/.idea/misc.xml
  Laboratorio1-Github/.idea/workspace.xml
  Laboratorio1-Github/Laboratorio1-Github.iml
  Laboratorio1-Github/WrongFile.txt
  Laboratorio1-Github/src/sumaTresCifras.java
Labels: isolated

#1 fix: New Function
  src/divide.jav
Labels: enhancement

#5 Development
  .gitignore
  .idea/misc.xml
  .idea/workspace.xml
  src/divide.jav
  src/sumaTresCifras.java
Labels: bug
